#!/bin/bash

if [ -f /etc/hostname-map.json ]
then
  MAP_FILE=/etc/hostname-map.json
elif [ -f /etc/hostname-automap/map.json ]
then
  MAP_FILE=/etc/hostname-automap/map.json
elif [ -f /usr/lib/hostname-automap/map.json ]
then
  MAP_FILE=/usr/lib/hostname-automap/map.json
else
  echo "map file not found"
  exit 1
fi

MAC_ADDRESS="$(ip link show e0 | awk '/ether/ {print $2}')"
NEW_HOSTNAME="$(jq -r '.["'$MAC_ADDRESS'"]' $MAP_FILE)"

hostnamectl hostname $NEW_HOSTNAME
